/* eslint-disable import/no-anonymous-default-export */
export default 
  {
  title1:"문제",
  text1:"- 사람들이 불편함을 느끼는 진짜 문제점",
  title2:"해결책",
  text2:"- 문제 해결을 위한 솔루션 개요",
  title3:"경쟁우위",
  text3:"- 다른제품이 쉽게 흉내낼수 없는 특징",
  title4:"가치제안",
  text4:"- 무심코 방문한 사람들을 잠재고객으로 바꾸는 분명하면서도 설득력있는 하나의 메시지",
  title5:"고객",
  text5:"- 타켓고객/가장 먼저 상품을 이용할 주요고객/목표시장 ",
  title6:"홍보채널",
  text6:"- SNS등 주로 사용하게 될 홍보방법",
  title7:"수익구조",
  text7:"- 매출이 발생되는 부분",
  title8:"비용구조",
  text8:"- 비용이 발생되는 부분",
  title9:"핵심지표",
  text9:"- 사업성과 확인을 위한 핵심지표",
  title10:"SWOT분석",
  text10:"- 강점(Strengths)",
  text11:"- 약점(Weaknesses)",
  text12:"- 기회(Opportunities) ",
  text13:"- 위기(Threats)",
  writer:"- 작성자",
}