/* eslint-disable import/no-anonymous-default-export */
export default [
  {title1:"대체하기(Substitute)",
  text1:"- 대체하거나 변경하면? \n(예:쇠젓가락을 나무젓가락으로)",
  title2:"결합하기(Combine)",
  text2:"- 두 부분을 결합하면? \n (예:지우개연필)",
  title3:"응용하기(Adapt)",
  text3:"- 응용해서 적용할 수 있는 부분은?\n (예:장미가시 응용-철조망 개발)",
  title4:"수정하기(Modify)",
  text4:"- 크기,모양,색,효과 등을 바꾸면? \n(예:포스트잇)",
  title5:"다른용도(Put another use)",
  text5:"- 다른 용도로 사용하면?\n (예:옥수수 연료)",
  title6:"제거하기(Eliminate)",
  text6:"- 부분을 삭제하거나 단순화 하면?\n (예:오픈카)",
  title7:"뒤집기(Reverse)",
  text7:"- 순서나 위치등을 뒤집으면?\n (예:누드김밥)",
  goodidea:"- 좋은 아이디어 3가지:",
  bestidea:"가장 좋은 최종아이디어",
  plusidea:"최종아이디어의 긍정적인 부분은?",
  minusidea:"최종아이디어의 부정적인 부분은?",
}, 
{title1:"분할하기",
  text1:"- 쪼개어 사용하면?\n (예:조립식가구,할부결제)",
  title2:"추출하기",
  text2:"- 필요한 부분만 뽑아내면?\n (예:김치냉장고,아웃소싱)",
  title3:"높이맞추기",
  text3:"- 사물을 편리한 위치에 맞추면?\n (예:문손잡이, 엘리베이터 버튼)",
  title4:"곡선화하기",
  text4:"- 직선을 곡선으로 바꾸면?\n (예:피자커팅칼)",
  title5:"선행조치",
  text5:"- 필요한 변화를 미리 준비하면?\n (예:에어컨필터,차량충돌구조)",
  title6:"주기적작용",
  text6:"- 연속 아닌 주기적으로 작용하면?\n (예:신호등,인체감지조명)",
  title7:"차원바꾸기",
  text7:"- 배치를 2,3차원으로 바꾸면?\n (예:사다리차,스텐드진열)",
  goodidea:"- 좋은 아이디어 3가지:",
  bestidea:"가장 좋은 최종아이디어",
  plusidea:"최종아이디어의 긍정적인 부분은?",
  minusidea:"최종아이디어의 부정적인 부분은?",
}
]