/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    work1:"벤치프레스",
    work2:"인클라인벤치프레스",
    work3:"디클라인벤치프레스",
   }, 
  {
    work1:"비하인드바벨프레스",
    work2:"프론트바벨프레스",
    work3:"밴트오버레터럴레이즈",
    work4:"사이드레터럴레이즈",
    work5:"업라이트로우",
  },
  {
    work1:"비하인드랫풀다운",
    work2:"프론트랫풀다운",
    work3:"턱걸이",
    work4:"바벨로우",
  },
  {
    work1:"케이블익스텐션",
    work2:"딥스",
    work3:"업라이드케이블익스텐션",
  },
  {
    work1:"덤벨컬",
    work2:"바벨컬",
    work3:"프리쳐컬",
  },
  {
    work1:"크런치",
    work2:"플랭크",
    work3:"V업",
    work4:"레그레이즈",
    work5:"전신크런치",
    work6:"니업",
  },
  {
    work1:"스쿼트",
    work2:"스쿼트니킥",
    work3:"스케이팅",
    work4:"텐션스쿼트",
    work5:"런지",
    work6:"스플릿 스쿼트",
  },
]